### ISSUE TITLE
Admin - Watchlist Tab Cassandra Integration

### ISSUE THREAD

**Issue by erikschlegel** [CatalystCode/project-fortis-interfaces#83]
Task Goal: Integrate existing `/Settings/siteTerms` graphql service endpoint into the Admin Module watchlist tab. This should encompass both read, write and removal capabilities. This will also involve adding a category field to the datagrid row in the Watchlist Tab. 
![image](https://user-images.githubusercontent.com/7635865/30968091-c36a5224-a423-11e7-85bf-dabfdb1d4568.png)

This tab already exists as well as the integration work with React Data Grid. All edit / remove / read functionality is also in place. 

*Newly added functionality*
- Add category field to the datagrid: The category field already exists in Cassandra, with valid data entries. This field is also being populated through the existing `/Settings/siteTerms`  service. The only work here is enhancing the grid field configuration and binding that field from the response to the grid. 
- As part of the save changes action  handler, we should create / publish a single message to the appropriate SB queue to raise the action to broadcast the keyword changes to all spark workers.
  
*Integration related dev work*
- re-point the old Fortis V1 watchlist service to the new service, and re-map the response payload to the existing grid component. 
- Refactor any needed changes to the existing cassandra `/Settings/addKeywords` or `/Settings/removeKeywords` GraphQL service. 
- Integrate both edit / remove services to the watchlist React component. 
- Remove Fluxxor integration for this component. All rendered data for this component should be populated from `this.props` as opposed to `this.state`. This should be a quick 4 line change. 
Remove these lines

```
import Fluxxor from 'fluxxor';

const FluxMixin = Fluxxor.FluxMixin(React);
const StoreWatchMixin = Fluxxor.StoreWatchMixin("AdminStore");
```

+ `mixins: [FluxMixin, StoreWatchMixin],`

the flux object should already be available as a component props, so ` this.getFlux().actions.ADMIN.load_topics(defaultLanguage);` -> ` this.props.flux.actions.ADMIN.load_topics(defaultLanguage);` 

It's good practice to use pure ES6 classes ie `export default class AdminWatchlist extends React.Component`

*Common Dev Tasks that's applicable for all dev tasks*
- Add proper log capturing in App Insights, as well as error / exception handling. 

*User Acceptance Testing checklist*
Please validate the below functionality. 
- Copy Watchlist terms from Excel to the Grid. You should validate the number of rows in the grid === old grid row length + excel source record count.
- Single records can be added / removed / edited. 
- Multiple selected rows can be added / removed / edited. 
- Translator feature is working for the selected rows. If a row is not selected then translation should ignore that term. 
- Once keywords are pasted from excel, and saved into the system via the watchlist tab... Export the Cassandra records into excel and run a data match comparison to make sure that the cassandra terms and excel terms are the same. The validation check should cover both the keyword in base language, translated keywords and category field. 
- Keyword filtering is still working in the grid. 
- Keyword Sorting is still working. 
- Grid row select all is working
- Confirm that a service bus message was dropped on the queue after save changes was selected. Confirm in the spark / scala code for the publishing target queue.
- the column names for the translated terms should be listed as `name_{site supported langs}`. The Cassandra output format should follow the existing convention of `{'lang_code': 'translated term'}`

Please provide the testing spreadsheet used for the data comparison as well as screenshots to illustrate the sort and filter features are fully functional.

**Comment by Smarker** [comment]
Service bus messages are being sent from services project to service bus:

![image](https://user-images.githubusercontent.com/7232635/31355236-70fd87d0-ad07-11e7-99a2-a3c1e4f035c4.png)
