### ISSUE TITLE
Implement Dashboard Authentication / Authorization

### ISSUE THREAD

**Issue by erikschlegel** [CatalystCode/project-fortis-interfaces#97]
*Task Goal*: 
Integrate @anastasiia-zolochevska Active Directory / Fortis PR for adding authentication / authorization for Fortis. This implementation will use the `adal-angular` npm mod to challenge a user for their security credentials if a site is configured as private. The PR can be found here https://github.com/CatalystCode/fortis-interface/pull/6/files .

*Background*: 
Every Fortis deployment requires an AD service principal tenant and app ID to be specified as part of the deployment. 

*Assumptions*
- There will be a GQL service endpoint available to provide a deployments AD Client ID and a boolean flag to drive whether the site requires authentication. Here's a sample GQL service call. 
```
fragment AuthSettingsView on AuthSettings {
                                 privateSite
                                 aadClientId
                             }
                             query AuthSettings($siteId: String!) {
                                authSettings: getAuthSettings(siteId: $siteId) {
                                     ...AuthSettingsView
                                 }
                             }
```

*Requirements*
- All non-Admin module Authentication checks should be disabled if the `privateSite` flag is set to false. The admin module should be AD authenticated irregardless of the privateSite setting.
- All dashboard, facts and admin react router routes(`src/routes/routes.js`) should be proxied through the authentication pre-check. 
- We'll need to grab the `adal.idtoken` off the cached user profile and set in the header for each Graph QL request. The Fortis GraphQL services will need to be enhanced to use the `passport-azure-ad` module to validate the token, via the bearer auth strategy(recommended as part of @mzxgiant security review). 
- In the event that the authentication check fails(ie service returning a `403`), then the front end should redirect the user to the AD user login page(via `authContext.login();`).
- We should perform an authorization admin role check for any requests made to the `/Admin` route. The authenticated user would need to be a member of the `Admin` AD role in order to gain access to the Admin module.

**Comment by c-w** [comment]
This has been implemented in [project-fortis](https://github.com/CatalystCode/project-fortis).
